DROP PROCEDURE IF EXISTS PR_ADD_INDEX;
DELIMITER //
/**
	增加索引，创建唯一索引时会检查是否有重复数据，如果存在重复数据则需手工编写脚本处理
		V_TABLE_NAME 表名
		V_INDEX_NAME 索引名
		V_INDEX_COL 索引涉及字段
		V_INDEX_TYPE 索引类型 0：普通索引，1：唯一索引
*/
CREATE PROCEDURE PR_ADD_INDEX(IN V_TABLE_NAME VARCHAR(40), 
							  IN V_INDEX_NAME VARCHAR(30),
							  IN V_INDEX_COL VARCHAR(200),
							  IN V_INDEX_TYPE TINYINT)
BEGIN
	-- 声名变量
 	DECLARE V_COUNT INT;
    DECLARE V_NON_UNIQUE INT;
    
    -- 查询表是否存在
 	SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = V_TABLE_NAME;
	IF V_COUNT = 1 THEN
		-- 查询索引是否存在
		SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_NAME = V_TABLE_NAME AND INDEX_NAME = V_INDEX_NAME;
        IF V_COUNT > 0 THEN
			SELECT CONCAT(V_TABLE_NAME, '表', V_INDEX_NAME, '索引已存在，请勿重复创建') err;
        ELSE -- 索引不存在则创建索引
			IF V_INDEX_TYPE = 0 THEN
				-- 创建普通索引
				SET @V_SQL = CONCAT(" ALTER TABLE ", V_TABLE_NAME, " ADD INDEX ", V_INDEX_NAME, "(", V_INDEX_COL, ")");
				PREPARE sqlStmt FROM @V_SQL;
				EXECUTE sqlStmt;
            ELSEIF V_INDEX_TYPE = 1 THEN
				-- 判断是否有重复数据
				-- SELECT MAX(b.con) con INTO V_NON_UNIQUE FROM (SELECT COUNT(1) con FROM t_bdmp_sys_manage_department GROUP BY org_name HAVING COUNT(org_name) > 1) b;
				SET @V_SQL = CONCAT(" SELECT MAX(b.con) con INTO @V_NON_UNIQUE FROM (SELECT COUNT(1) con FROM ", V_TABLE_NAME, " GROUP BY ", V_INDEX_COL, " HAVING COUNT(1) > 1) b");
				PREPARE sqlStmt FROM @V_SQL;
				EXECUTE sqlStmt;
				DEALLOCATE PREPARE sqlStmt;
				set V_NON_UNIQUE = @V_NON_UNIQUE;
				IF V_NON_UNIQUE > 0 THEN
					SELECT CONCAT(V_TABLE_NAME, '表', V_INDEX_COL, '列，存在重复数据，无法创建唯一索引') err;
                ELSE
					-- 创建唯一索引
					SET @V_SQL = CONCAT(" ALTER TABLE ", V_TABLE_NAME, " ADD UNIQUE INDEX ", V_INDEX_NAME, "(", V_INDEX_COL, ")");
					PREPARE sqlStmt FROM @V_SQL;
					EXECUTE sqlStmt;
                END IF;
            END IF;
		END IF;
    END IF;
END;
//
DELIMITER ;
