DROP PROCEDURE IF EXISTS PR_DEL_INDEX;
DELIMITER //
/**
	删除索引
		V_TABLE_SCHEMA 数据库名
		V_TABLE_NAME 表名
		V_INDEX_NAME 索引名
*/
CREATE PROCEDURE PR_DEL_INDEX(
	IN V_TABLE_SCHEMA VARCHAR(50),
	IN V_TABLE_NAME VARCHAR(40),
	IN V_INDEX_NAME VARCHAR(30)
)
BEGIN
	-- 声名变量
 	DECLARE V_COUNT INT;
    
    -- 查询表是否存在
 	SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = V_TABLE_NAME AND TABLE_SCHEMA = V_TABLE_SCHEMA;
	IF V_COUNT = 1 THEN
		-- 查询索引是否存在
		SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_NAME = V_TABLE_NAME AND TABLE_SCHEMA = V_TABLE_SCHEMA AND INDEX_NAME = V_INDEX_NAME;
        IF V_COUNT > 0 THEN
            -- 索引存在则删除索引
			SET @V_SQL = CONCAT(" ALTER TABLE ", V_TABLE_SCHEMA, ".", V_TABLE_NAME, " DROP INDEX ", V_INDEX_NAME);
			PREPARE sqlStmt FROM @V_SQL;
			EXECUTE sqlStmt;
        END IF;    
    END IF;
END;
//
DELIMITER ;
