DROP PROCEDURE IF EXISTS PR_DEL_COLUMN;
DELIMITER //
/**
	删除字段
		V_TABLE_NAME 表名
		V_COL_NAME 字段名
*/
CREATE PROCEDURE PR_DEL_COLUMN(IN V_TABLE_NAME VARCHAR(40),
							   IN V_COL_NAME VARCHAR(30))
BEGIN
	-- 声名变量
 	DECLARE V_COUNT INT;
    DECLARE V_COL_FINAL_SCALE VARCHAR(20);
  
    -- 查询表是否存在
 	SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = V_TABLE_NAME;
	IF V_COUNT = 1 THEN
		-- 查询字段列是否存在
		SELECT COUNT(1) INTO V_COUNT FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME = V_TABLE_NAME AND COLUMN_NAME = V_COL_NAME;
		-- 字段存在则删除字段
		IF V_COUNT = 1 THEN
			SET @V_SQL = CONCAT(" ALTER TABLE ", V_TABLE_NAME, " DROP COLUMN ", V_COL_NAME);
			PREPARE sqlStmt FROM @V_SQL;
			EXECUTE sqlStmt;
        END IF;    
    END IF;
END;
//
DELIMITER ;
